@startuml
class com.ssafy.enjoytrip.attraction.dto.AttractionDto {
- int attractionId
- int contentTypeId
- String title
- String addr1
- String addr2
- String zipcode
- String tel
- String firstImage
- String firstImage2
- int readcount
- int sidoCode
- int gugunCode
- double latitude
- double longitude
- String mlevel
+ int getAttractionId()
+ void setAttractionId(int)
+ int getContentTypeId()
+ void setContentTypeId(int)
+ String getTitle()
+ void setTitle(String)
+ String getAddr1()
+ void setAddr1(String)
+ String getAddr2()
+ void setAddr2(String)
+ String getZipcode()
+ void setZipcode(String)
+ String getTel()
+ void setTel(String)
+ String getFirstImage()
+ void setFirstImage(String)
+ String getFirstImage2()
+ void setFirstImage2(String)
+ int getSidoCode()
+ void setSidoCode(int)
+ int getGugunCode()
+ void setGugunCode(int)
+ double getLatitude()
+ void setLatitude(double)
+ double getLongitude()
+ void setLongitude(double)
+ int getReadcount()
+ void setReadcount(int)
+ String getMlevel()
+ void setMlevel(String)
+ String toString()
}
class com.ssafy.enjoytrip.attraction.dto.SidoDto {
- int sidoCode
- String sidoName
+ int getSidoCode()
+ void setSidoCode(int)
+ String getSidoName()
+ void setSidoName(String)
+ String toString()
}
interface com.ssafy.enjoytrip.attraction.service.AttractionService {
~ List<SidoDto> getSidoList()
~ List<GugunDto> getGugunList()
~ List<AttractionDto> getAttractionList(Map<String,Object>)
~ List<AttractionDto> getHotplaceList(Map<String,Object>)
}
class com.ssafy.enjoytrip.attraction.service.AttractionServiceImpl {
- AttractionMapper attractionMapper
+ List<SidoDto> getSidoList()
+ List<GugunDto> getGugunList()
+ List<AttractionDto> getAttractionList(Map<String,Object>)
+ List<AttractionDto> getHotplaceList(Map<String,Object>)
}
class com.ssafy.enjoytrip.attraction.dto.GugunDto {
- int gugunCode
- String gugunName
- int sidoCode
+ int getGugunCode()
+ void setGugunCode(int)
+ String getGugunName()
+ void setGugunName(String)
+ int getSidoCode()
+ void setSidoCode(int)
+ String toString()
}
interface com.ssafy.enjoytrip.attraction.mapper.AttractionMapper {
~ List<SidoDto> getSidoList()
~ List<GugunDto> getGugunList()
~ List<AttractionDto> getAttractionList(Map<String,Object>)
~ List<AttractionDto> getHotplaceList(Map<String,Object>)
}
class com.ssafy.enjoytrip.attraction.controller.AttractionController {
- AttractionService attractionService
+ ResponseEntity<?> getAttractionList(Integer,Integer,Integer,String)
+ ResponseEntity<?> getSidoList()
+ ResponseEntity<?> getGugunList()
+ ResponseEntity<?> getHotplaceList(Integer,Integer,Integer,String)
- ResponseEntity<String> exceptionHandling(Exception)
}


com.ssafy.enjoytrip.attraction.service.AttractionService <|.. com.ssafy.enjoytrip.attraction.service.AttractionServiceImpl
@enduml