@startuml
class com.ssafy.enjoytrip.global.config.SwaggerConfiguration {
- String version
- String title
+ Docket api()
- Set<String> getConsumeContentTypes()
- Set<String> getProduceContentTypes()
- ApiInfo apiInfo()
}
class com.ssafy.enjoytrip.global.aop.LoggingAspect {
}
class com.ssafy.enjoytrip.global.interceptor.ConfirmInterceptor {
}
class com.ssafy.enjoytrip.global.config.WebMvcConfiguration {
}
@enduml