@startuml
interface com.ssafy.enjoytrip.plan.mapper.PlanMapper {
~ void addPlan(PlanDto)
~ List<PlanDto> getPlanList(String)
~ void deletePlan(String)
~ void updatePlan(PlanDto)
~ PlanDto getPlan(String)
~ void addRoute(String,List<Map<String,Object>>)
}
class com.ssafy.enjoytrip.plan.controller.PlanController {
- PlanService planService
+ ResponseEntity<?> addPlan(PlanDto)
+ ResponseEntity<?> getPlanList(String)
+ ResponseEntity<?> deletePlan(String)
+ ResponseEntity<?> updatePlan(PlanDto)
+ ResponseEntity<?> getPlan(String)
+ ResponseEntity<?> addRoute(String,Map<String,Object>)
- ResponseEntity<String> exceptionHandling(Exception)
}
interface com.ssafy.enjoytrip.plan.service.PlanService {
~ void addPlan(PlanDto)
~ List<PlanDto> getPlanList(String)
~ void deletePlan(String)
~ void updatePlan(PlanDto)
~ PlanDto getPlan(String)
~ void addRoute(String,List<Map<String,Object>>)
}
class com.ssafy.enjoytrip.plan.service.PlanServiceImpl {
- PlanMapper planMapper
+ void addPlan(PlanDto)
+ List<PlanDto> getPlanList(String)
+ void deletePlan(String)
+ void updatePlan(PlanDto)
+ PlanDto getPlan(String)
+ void addRoute(String,List<Map<String,Object>>)
}
class com.ssafy.enjoytrip.plan.dto.PlanDto {
- int planId
- String userId
- String planTitle
- String startDate
- String endDate
- int complete
+ int getPlanId()
+ void setPlanId(int)
+ String getUserId()
+ void setUserId(String)
+ String getPlanTitle()
+ void setPlanTitle(String)
+ String getStartDate()
+ void setStartDate(String)
+ String getEndDate()
+ void setEndDate(String)
+ int getComplete()
+ void setComplete(int)
+ String toString()
}


com.ssafy.enjoytrip.plan.service.PlanService <|.. com.ssafy.enjoytrip.plan.service.PlanServiceImpl
@enduml